resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: 
  - msbuild
  - visualstudio
  - vstest

variables:
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  System.Debug: 'false'
  Parameters.Solution: IEXDotNet
  NugetApiKey: oy2ddvn5an4zeiqchg7ar65q2ilws3mujdx3xqxod65ivy

steps:
- script: |
    dotnet restore
    dotnet build --output $(Build.ArtifactStagingDirectory)
    dotnet test
    dotnet pack --output $(Build.ArtifactStagingDirectory) -c Release /p:Version=1.0.$(Build.BuildId)
- task: PublishBuildArtifacts@1
  displayName: publish artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'

- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies' # Options: testAssemblies, testPlan, testRun
    testAssemblyVer2: | # Required when testSelector == TestAssemblies
     **\*Test*.dll
     !**\*TestAdapter.dll
     !**\obj\** 
    
- task: DotNetCoreCLI@2
  displayName: dotnet nuget push
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: custom
    custom: nuget
    arguments: push $(Build.ArtifactStagingDirectory)\*.nupkg --source https://www.nuget.org --api-key $(NugetApiKey)